version: "3"
services:
  mysql-db:
    container_name: mysql_db
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petStoreDB
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  database:
# docker compose --env-file ../.env up
# docker compose start
