// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CRUD_HAPPY_PET.Models;

public partial class Pet
{
    [DisplayName("Pet ID")]
    public sbyte PetId { get; set; }

    [DisplayName("Pet Name")]
    [Required(ErrorMessage = "Pet Name is required")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Pet name must be between 3 and 50 charatset")]
    public string PetName { get; set; }

    [DisplayName("Pet Type")]
    [Required(ErrorMessage = "Pet Type is required")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Pet name must be between 3 and 50 charatset")]
    public string PetType { get; set; }

    [DisplayName("Pet Colour")]
    [Required(ErrorMessage = "Pet Colour is required")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Pet name must be between 3 and 50 charatset")]
    public string PetColour { get; set; }
}