// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRUD_HAPPY_PET.Models;

public partial class petStoreDBContext : DbContext
{
    public petStoreDBContext(DbContextOptions<petStoreDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Pet> Pets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("latin1_swedish_ci");

        modelBuilder.Entity<Pet>(entity =>
        {
            entity.HasKey(e => e.PetId).HasName("PRIMARY");

            entity.ToTable("Pet");

            entity.Property(e => e.PetId)
                .HasColumnType("tinyint(50)")
                .HasColumnName("Pet_Id");
            entity.Property(e => e.PetColour)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Pet_Colour");
            entity.Property(e => e.PetName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Pet_Name");
            entity.Property(e => e.PetType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("Pet_Type");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}